module HA_ave(
	p0,
	p1,
	p2,
	p3,
	p4,
	mem_cnt0,
	mem_cnt1,
	mem_cnt2,
	mem_cnt3,
	wrong_adder);

	//---Ports declearation: generated by Robei---
	input [15:0] p0;
	input [15:0] p1;
	input [15:0] p2;
	input [15:0] p3;
	output [15:0] p4;
	input mem_cnt0;
	input mem_cnt1;
	input mem_cnt2;
	input mem_cnt3;
	output wrong_adder;

	wire [15:0] p0;
	wire [15:0] p1;
	wire [15:0] p2;
	wire [15:0] p3;
	reg [15:0] p4;
	wire mem_cnt0;
	wire mem_cnt1;
	wire mem_cnt2;
	wire mem_cnt3;
	reg wrong_adder;

	//----Code starts here: integrated by Robei-----
	always @(*) begin
	if((mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3)!=0) begin
	p4=(p0+p1+p2+p3)/(mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3);
	end
	else begin
	wrong_adder=1;
	end
	end
	/*if((mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3)!=0) begin
	if((mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3)==3) begin
	p4=(p0*mem_cnt0+p1*mem_cnt1+p2*mem_cnt2+p3*mem_cnt3)/(mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3);
	end
	else if((mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3)==4) begin
	//p4=(p0+p1+p2+p3)/(mem_cnt0+mem_cnt1+mem_cnt2+mem_cnt3);
	end*/
endmodule    //HA_ave

