module Kalmenfilter(
	ResrcData,
	x_out);

	//---Ports declearation: generated by Robei---
	input [15:0] ResrcData;
	output [15:0] x_out;

	wire [15:0] ResrcData;
	wire [15:0] x_out;

	//----Code starts here: integrated by Robei-----
	               reg signed[15:0]   x_mid,x_now;
	reg signed[15:0] x_last;
	 real p_last,p_mid,p_now,kg;
	reg ctr;
	parameter Q=3;
	parameter R=10;
	initial begin
	ctr<=0;
	#1 ctr<=1;
	end
	always @(*)
	begin
	if (!ctr)
	begin
	p_last=1;
	x_last=0;
	end
	else begin
	             x_mid = x_last;                       //x_last=x(k-1|k-1),x_mid=x(k|k-1)
	             p_mid = p_last + Q;                     //p_mid=p(k|k-1),p_last=p(k-1|k-1),Q=??
	             kg = p_mid / (p_mid + R);                 //kg?kalman filter,R ???
	             x_now = x_mid + kg * $signed((ResrcData - x_mid));   //???????  
	             p_now = (1 - kg) * p_mid;                 //??????covariance
	             p_last = p_now;                     //??covariance ?
	             x_last = x_now;                     //???????	
	         //   x_out=x_now;
	end
	    end
	 assign x_out=x_now;
endmodule    //Kalmenfilter

